### ISSUE TITLE
[1.12] Mod prints Server Crash Report in the Console without a Crash

### ISSUE THREAD

**Issue by MasterEnderman** [aksource/EnchantChanger#1]
The mod prints randomly a crash report into the server console. But the server doesn't crash.
Crash-Report: https://pastebin.com/MFte0YeV
EnchantChanger: 1.9.11
Forge: 14.23.1.2606

**Comment by aksource** [comment]
@MasterEnderman 
Thank you for your crash report.
But I don't know why Client Side Class loaded on Server Side.
Please test again without other mod.

(add)
I found what causes the bug.
I'll fix it next release.

**Comment by aksource** [comment]
I fixed it on 1.12-1.9.13.
Close.
