### ISSUE TITLE
[1.12] Player gets Invisible after holding a Item from EnchantChanger

### ISSUE THREAD

**Issue by MasterEnderman** [aksource/EnchantChanger#2]
I'm owning a server and we use your mod. But every time a player holds an Item from your mod he becomes invisible, until he reconnects.

Forge: 14.23.1.2606
EnchantChanger: 1.9.11

**Comment by aksource** [comment]
@MasterEnderman 
Maybe.. It is my mod's rendering problem.
But I can't test SMP.
Anyway, I try to fix it.

**Comment by aksource** [comment]
@MasterEnderman 
I play SMP but I can't verify what you reported.
Please, try SMP with Forge and EnchantChanger only.

**Comment by MasterEnderman** [comment]
it still happens with only forge and enchantchanger. i let two people stay next to each other and as soon as one of them takes one of the swords or a materia in the hand the player vanishes and only reappears after he reconnects. But after holding one of those items again. He becomes invisible again.

**Comment by aksource** [comment]
@MasterEnderman 
I tested it with Forge 1.12.2-14.23.1.2606 on dev environment but I couldn't.
I will fix some code about rendering next release.
Please wait and try again.

**Comment by MasterEnderman** [comment]
Hopefully this also fixes the fps drop if you hold one of the swords.

**Comment by aksource** [comment]
I think I could fix it on 1.12-1.9.13.
Please check your own environment.
