### ISSUE TITLE
[Suggestion] Union Sword Damage/effect?

### ISSUE THREAD

**Issue by MasterEnderman** [aksource/EnchantChanger#4]
the damage of the union sword should be the damage of all the 5 swords added together. Or has it any other special effect? I mean you can cycle through the different swords, but they don't change anything?

**Comment by aksource** [comment]
>the damage of the union sword should be the damage of all the 5 swords added together.

The first sword(Attack mode) has that function.

>Or has it any other special effect? I mean you can cycle through the different swords, but they don't change anything?

If you want to change swords in the union sword, you need to "release swords".
I think the union sword is a container of first sword and other swords.
The first sword is a most powerful sword of EnchantChanger.
